const XLSX = require('xlsx');

const rows = [
  ['D1', 'Medical Leave & Flexibility', 1, 'Paid medical leave beyond local / legal requirements', ''],
  ['D1', 'Medical Leave & Flexibility', 2, 'Intermittent leave beyond local / legal requirements', ''],
  ['D1', 'Medical Leave & Flexibility', 3, 'Flexible work hours during treatment (e.g., varying start/end times, compressed schedules)', ''],
  ['D1', 'Medical Leave & Flexibility', 4, 'Remote work options for on-site employees', ''],
  ['D1', 'Medical Leave & Flexibility', 5, 'Reduced schedule/part-time with full benefits', ''],
  ['D1', 'Medical Leave & Flexibility', 6, 'Job protection beyond local / legal requirements', ''],
  ['D1', 'Medical Leave & Flexibility', 7, 'Emergency leave within 24 hours', ''],
  ['D1', 'Medical Leave & Flexibility', 8, 'Leave donation bank (employees can donate PTO to colleagues)', ''],
  ['D1', 'Medical Leave & Flexibility', 9, 'Disability pay top-up (employer adds to disability insurance)', ''],
  ['D1', 'Medical Leave & Flexibility', 10, 'PTO accrual during leave', ''],
  ['D1', 'Medical Leave & Flexibility', 11, 'Paid micro-breaks for medical-related side effects', ''],
  ['D1', 'Medical Leave & Flexibility', 12, 'Full salary (100%) continuation during cancer-related short-term disability leave', ''],
  ['D1', 'Medical Leave & Flexibility', 13, 'Guaranteed full salary and health insurance continuation for a defined period', 'NEW'],
  ['D1', 'Medical Leave & Flexibility', 14, 'Guaranteed job protection for a defined period', 'NEW'],
  ['D2', 'Insurance & Financial Protection', 1, 'Coverage for clinical trials and experimental treatments not covered by standard health insurance', ''],
  ['D2', 'Insurance & Financial Protection', 2, 'Coverage for advanced therapies (CAR-T, proton therapy, immunotherapy) not covered by standard health insurance', ''],
  ['D2', 'Insurance & Financial Protection', 3, 'Paid time off for clinical trial participation', ''],
  ['D2', 'Insurance & Financial Protection', 4, 'Set out-of-pocket maximums (for in-network single coverage)', ''],
  ['D2', 'Insurance & Financial Protection', 5, 'Travel/lodging reimbursement for specialized care beyond insurance coverage', ''],
  ['D2', 'Insurance & Financial Protection', 6, 'Financial counseling services', ''],
  ['D2', 'Insurance & Financial Protection', 7, 'Voluntary supplemental illness insurance (with employer contribution)', ''],
  ['D2', 'Insurance & Financial Protection', 8, 'Real-time cost estimator tools', ''],
  ['D2', 'Insurance & Financial Protection', 9, 'Insurance advocacy/pre-authorization support', ''],
  ['D2', 'Insurance & Financial Protection', 10, '$0 copay for specialty drugs', ''],
  ['D2', 'Insurance & Financial Protection', 11, 'Hardship grants program funded by employer', ''],
  ['D2', 'Insurance & Financial Protection', 12, 'Tax/estate planning assistance', ''],
  ['D2', 'Insurance & Financial Protection', 13, 'Short-term disability covering 60%+ of salary', ''],
  ['D2', 'Insurance & Financial Protection', 14, 'Long-term disability covering 60%+ of salary', ''],
  ['D2', 'Insurance & Financial Protection', 15, 'Employer-paid disability insurance supplements', ''],
  ['D2', 'Insurance & Financial Protection', 16, 'Guaranteed job protection', ''],
  ['D2', 'Insurance & Financial Protection', 17, 'Accelerated life insurance benefits (partial payout for terminal / critical illness)', ''],
  ['D3', 'Manager Preparedness & Capability', 1, 'Manager training on supporting employees managing cancer or other serious health conditions/illnesses and their teams', ''],
  ['D3', 'Manager Preparedness & Capability', 2, 'Clear escalation protocol for manager response', ''],
  ['D3', 'Manager Preparedness & Capability', 3, 'Dedicated manager resource hub', ''],
  ['D3', 'Manager Preparedness & Capability', 4, 'Empathy/communication skills training', ''],
  ['D3', 'Manager Preparedness & Capability', 5, 'Legal compliance training', ''],
  ['D3', 'Manager Preparedness & Capability', 6, 'Senior leader coaching on supporting impacted employees', ''],
  ['D3', 'Manager Preparedness & Capability', 7, 'Manager evaluations include how well they support impacted employees', ''],
  ['D3', 'Manager Preparedness & Capability', 8, 'Manager peer support / community building', ''],
  ['D3', 'Manager Preparedness & Capability', 9, 'AI-powered guidance tools', ''],
  ['D3', 'Manager Preparedness & Capability', 10, 'Privacy protection and confidentiality management', ''],
  ['D4', 'Specialized Resources', 1, 'Dedicated navigation support to help employees understand benefits and access medical care', ''],
  ['D4', 'Specialized Resources', 2, 'Benefits optimization assistance (maximizing coverage, minimizing costs)', ''],
  ['D4', 'Specialized Resources', 3, 'Insurance advocacy/appeals support', ''],
  ['D4', 'Specialized Resources', 4, 'Clinical trial matching service', ''],
  ['D4', 'Specialized Resources', 5, 'Care coordination concierge', ''],
  ['D4', 'Specialized Resources', 6, 'Online tools, apps, or portals for health/benefits support', ''],
  ['D4', 'Specialized Resources', 7, 'Survivorship planning assistance', ''],
  ['D4', 'Specialized Resources', 8, 'Physical rehabilitation support', ''],
  ['D4', 'Specialized Resources', 9, 'Occupational therapy/vocational rehabilitation', ''],
  ['D4', 'Specialized Resources', '-', 'Nutrition coaching', 'REMOVED'],
  ['D5', 'Workplace Accommodations & Modifications', 1, 'Physical workspace modifications', ''],
  ['D5', 'Workplace Accommodations & Modifications', 2, 'Cognitive / fatigue support tools', ''],
  ['D5', 'Workplace Accommodations & Modifications', 3, 'Ergonomic equipment funding', ''],
  ['D5', 'Workplace Accommodations & Modifications', 4, 'Rest areas / quiet spaces', ''],
  ['D5', 'Workplace Accommodations & Modifications', 5, 'Temporary role redesigns', ''],
  ['D5', 'Workplace Accommodations & Modifications', 6, 'Assistive technology catalog', ''],
  ['D5', 'Workplace Accommodations & Modifications', 7, 'Transportation reimbursement', ''],
  ['D5', 'Workplace Accommodations & Modifications', 8, 'Policy accommodations (e.g., dress code flexibility, headphone use)', ''],
  ['D5', 'Workplace Accommodations & Modifications', '-', 'Priority parking', 'REMOVED'],
  ['D5', 'Workplace Accommodations & Modifications', '-', 'Remote work capability', 'REMOVED (duplicate of D1)'],
  ['D5', 'Workplace Accommodations & Modifications', '-', 'Flexible scheduling options', 'REMOVED (similar to D8)'],
  ['D6', 'Culture & Psychological Safety', 1, 'Strong anti-discrimination policies specific to health conditions', ''],
  ['D6', 'Culture & Psychological Safety', 2, 'Clear process for confidential health disclosures', ''],
  ['D6', 'Culture & Psychological Safety', 3, 'Manager training on handling sensitive health information', ''],
  ['D6', 'Culture & Psychological Safety', 4, 'Written anti-retaliation policies for health disclosures', ''],
  ['D6', 'Culture & Psychological Safety', 5, 'Employee peer support groups (internal employees with shared experience)', ''],
  ['D6', 'Culture & Psychological Safety', 6, 'Professional-led support groups (external facilitator/counselor)', ''],
  ['D6', 'Culture & Psychological Safety', 7, 'Stigma-reduction initiatives', ''],
  ['D6', 'Culture & Psychological Safety', 8, 'Specialized emotional counseling', ''],
  ['D6', 'Culture & Psychological Safety', 9, 'Optional open health dialogue forums', ''],
  ['D6', 'Culture & Psychological Safety', 10, 'Inclusive communication guidelines', ''],
  ['D6', 'Culture & Psychological Safety', 11, 'Confidential HR channel for health benefits, policies and insurance-related questions', ''],
  ['D6', 'Culture & Psychological Safety', 12, 'Anonymous benefits navigation tool or website (no login required)', ''],
  ['D7', 'Career Continuity & Advancement', 1, 'Continued access to training/development', ''],
  ['D7', 'Career Continuity & Advancement', 2, 'Structured reintegration programs', ''],
  ['D7', 'Career Continuity & Advancement', 3, 'Peer mentorship program (employees who had similar condition mentoring current employees)', ''],
  ['D7', 'Career Continuity & Advancement', 4, 'Professional coach/mentor for employees managing cancer or other serious health conditions', ''],
  ['D7', 'Career Continuity & Advancement', 5, 'Adjusted performance goals/deliverables during treatment and recovery', ''],
  ['D7', 'Career Continuity & Advancement', 6, 'Career coaching for employees managing cancer or other serious health conditions', ''],
  ['D7', 'Career Continuity & Advancement', 7, 'Succession planning protections', ''],
  ['D7', 'Career Continuity & Advancement', 8, 'Project continuity protocols', ''],
  ['D7', 'Career Continuity & Advancement', 9, 'Optional stay-connected program', ''],
  ['D8', 'Work Continuation & Resumption', 1, 'Phased return-to-work plans', ''],
  ['D8', 'Work Continuation & Resumption', 2, 'Workload adjustments during treatment', ''],
  ['D8', 'Work Continuation & Resumption', 3, 'Flexibility for medical setbacks', ''],
  ['D8', 'Work Continuation & Resumption', 4, 'Buddy/mentor pairing for support', ''],
  ['D8', 'Work Continuation & Resumption', 5, 'Structured progress reviews', ''],
  ['D8', 'Work Continuation & Resumption', 6, 'Contingency planning for treatment schedules', ''],
  ['D8', 'Work Continuation & Resumption', 7, 'Long-term success tracking', ''],
  ['D8', 'Work Continuation & Resumption', 8, 'Access to occupational therapy/vocational rehabilitation', ''],
  ['D8', 'Work Continuation & Resumption', 9, 'Online peer support forums', ''],
  ['D8', 'Work Continuation & Resumption', 10, 'Access to specialized work resumption professionals', ''],
  ['D8', 'Work Continuation & Resumption', 11, 'Manager training on supporting team members during treatment/return', ''],
  ['D8', 'Work Continuation & Resumption', '-', 'Flexible work arrangements during treatment', 'REMOVED (overlaps D1 + other D8)'],
  ['D9', 'Executive Commitment & Resources', 1, 'Executive accountability metrics', ''],
  ['D9', 'Executive Commitment & Resources', 2, 'Public success story celebrations', ''],
  ['D9', 'Executive Commitment & Resources', 3, 'Compensation tied to support outcomes', ''],
  ['D9', 'Executive Commitment & Resources', 4, 'ESG/CSR reporting inclusion', ''],
  ['D9', 'Executive Commitment & Resources', 5, 'Year-over-year budget growth', ''],
  ['D9', 'Executive Commitment & Resources', 6, 'Executive sponsors communicate regularly about workplace support programs', ''],
  ['D9', 'Executive Commitment & Resources', 7, 'Dedicated budget allocation for serious illness support programs', ''],
  ['D9', 'Executive Commitment & Resources', 8, 'C-suite executive serves as program champion/sponsor', ''],
  ['D9', 'Executive Commitment & Resources', 9, 'Support programs included in investor/stakeholder communications', ''],
  ['D9', 'Executive Commitment & Resources', 10, 'Cross-functional executive steering committee for workplace support programs', ''],
  ['D9', 'Executive Commitment & Resources', 11, 'Support metrics included in annual report/sustainability reporting', ''],
  ['D9', 'Executive Commitment & Resources', 12, 'Executive-led town halls focused on health benefits and employee support', ''],
  ['D10', 'Caregiver & Family Support', 1, 'Paid caregiver leave with expanded eligibility (beyond local legal requirements)', ''],
  ['D10', 'Caregiver & Family Support', 2, 'Flexible work arrangements for caregivers', ''],
  ['D10', 'Caregiver & Family Support', 3, 'Dependent care subsidies', ''],
  ['D10', 'Caregiver & Family Support', 4, 'Emergency caregiver funds', ''],
  ['D10', 'Caregiver & Family Support', 5, 'Dependent care account matching/contributions', ''],
  ['D10', 'Caregiver & Family Support', 6, 'Family navigation support', ''],
  ['D10', 'Caregiver & Family Support', 7, 'Caregiver peer support groups', ''],
  ['D10', 'Caregiver & Family Support', 8, 'Mental health support specifically for caregivers', ''],
  ['D10', 'Caregiver & Family Support', 9, 'Manager training for supervising caregivers', ''],
  ['D10', 'Caregiver & Family Support', 10, 'Practical support for managing caregiving and work', ''],
  ['D10', 'Caregiver & Family Support', 11, 'Emergency dependent care when regular arrangements unavailable', ''],
  ['D10', 'Caregiver & Family Support', 12, 'Respite care funding/reimbursement', ''],
  ['D10', 'Caregiver & Family Support', 13, 'Caregiver resource navigator/concierge', ''],
  ['D10', 'Caregiver & Family Support', 14, 'Legal/financial planning assistance for caregivers', ''],
  ['D10', 'Caregiver & Family Support', 15, 'Modified job duties during peak caregiving periods', ''],
  ['D10', 'Caregiver & Family Support', 16, 'Unpaid leave job protection beyond local / legal requirements', ''],
  ['D10', 'Caregiver & Family Support', 17, 'Eldercare consultation and referral services', ''],
  ['D10', 'Caregiver & Family Support', 18, 'Paid time off for care coordination appointments', ''],
  ['D10', 'Caregiver & Family Support', 19, 'Expanded caregiver leave eligibility beyond legal definitions (e.g., siblings, in-laws, chosen family)', ''],
  ['D10', 'Caregiver & Family Support', 20, 'Concierge services to coordinate caregiving logistics (e.g., scheduling, transportation, home care)', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 1, 'At least 70% coverage for regionally / locally recommended screenings', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 2, 'Full or partial coverage for annual health screenings/checkups', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 3, 'Targeted risk-reduction programs', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 4, 'Paid time off for preventive care appointments', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 5, 'Legal protections beyond requirements', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 6, 'Workplace safety assessments to minimize health risks', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 7, 'Regular health education sessions', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 8, 'Individual health assessments (online or in-person)', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 9, 'Genetic screening/counseling', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 10, 'On-site vaccinations', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 11, 'Lifestyle coaching programs', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 12, 'Risk factor tracking/reporting', ''],
  ['D11', 'Prevention, Wellness & Legal Compliance', 13, 'Policies to support immuno-compromised colleagues (e.g., mask protocols, ventilation)', ''],
  ['D12', 'Continuous Improvement & Outcomes', 1, 'Return-to-work success metrics', ''],
  ['D12', 'Continuous Improvement & Outcomes', 2, 'Employee satisfaction tracking', ''],
  ['D12', 'Continuous Improvement & Outcomes', 3, 'Business impact/ROI assessment', ''],
  ['D12', 'Continuous Improvement & Outcomes', 4, 'Regular program enhancements', ''],
  ['D12', 'Continuous Improvement & Outcomes', 5, 'External benchmarking', ''],
  ['D12', 'Continuous Improvement & Outcomes', 6, 'Innovation pilots', ''],
  ['D12', 'Continuous Improvement & Outcomes', 7, 'Employee confidence in employer support', ''],
  ['D12', 'Continuous Improvement & Outcomes', 8, 'Program utilization analytics', ''],
  ['D12', 'Continuous Improvement & Outcomes', 9, 'Measure screening campaign ROI (e.g., participation rates, inquiries about access, etc.)', ''],
  ['D13', 'Communication & Awareness', 1, 'Proactive communication at point of diagnosis disclosure', ''],
  ['D13', 'Communication & Awareness', 2, 'Dedicated program website or portal', ''],
  ['D13', 'Communication & Awareness', 3, 'Regular company-wide awareness campaigns (at least quarterly)', ''],
  ['D13', 'Communication & Awareness', 4, 'New hire orientation coverage', ''],
  ['D13', 'Communication & Awareness', 5, 'Manager toolkit for cascade communications', ''],
  ['D13', 'Communication & Awareness', 6, 'Employee testimonials/success stories', ''],
  ['D13', 'Communication & Awareness', 7, 'Multi-channel communication strategy', ''],
  ['D13', 'Communication & Awareness', 8, 'Family/caregiver communication inclusion', ''],
  ['D13', 'Communication & Awareness', 9, 'Ability to access program information and resources anonymously', ''],
  ['D13', 'Communication & Awareness', 10, 'Cancer awareness month campaigns with resources', ''],
];

const wb = XLSX.utils.book_new();

// ===== Sheet 1: Elements =====
const elemHeader = ['Dimension', 'Dimension Name', '#', 'Element', 'Status', 'Rebecca Notes / Edits'];
const elemData = [elemHeader, ...rows.map(r => [r[0], r[1], r[2], r[3], r[4], ''])];
const ws1 = XLSX.utils.aoa_to_sheet(elemData);
ws1['!cols'] = [
  { wch: 10 },  // Dimension
  { wch: 38 },  // Dimension Name
  { wch: 4 },   // #
  { wch: 80 },  // Element
  { wch: 28 },  // Status
  { wch: 40 },  // Rebecca Notes
];
XLSX.utils.book_append_sheet(wb, ws1, 'Elements');

// ===== Sheet 2: Scale Mapping =====
const scaleData = [
  ['Response Scale Mapping: 2026 to 2027'],
  [],
  ['2027 Response Option', 'Definition', 'Points'],
  ['In Place', 'This program, policy, or practice is currently active and available to employees.', '5'],
  ['In Development', 'A formal plan exists and resources have been allocated to implement this within the next 12-18 months.', '3'],
  ['Under Review', 'Actively evaluating the feasibility, cost, or design of this program. No implementation timeline yet, but it is on leadership\'s radar.', '2'],
  ['Open to Exploring (NEW)', 'Had not considered this, but learning about it has sparked interest. Open to reviewing whether this could work for your organization.', 'TBD (recommend 1)'],
  ['Not Planned', 'Considered this and determined it is not feasible or appropriate for your organization at this time.', '0'],
  ['Unsure (currently hidden)', 'Don\'t have enough information to answer this accurately. Flags the item for internal follow-up.', 'TBD (was 0)'],
  [],
  ['2026 to 2027 Mapping'],
  [],
  ['Old Response (2026)', 'Maps To (2027)', 'Rationale'],
  ['Currently offer / Implemented / Measuring and reporting / Currently use', 'In Place', 'Direct equivalent - program exists and is active'],
  ['Plan to offer within 12 months / In active planning / Planning measurement', 'In Development', 'Both indicate committed plans with allocated resources'],
  ['Assessing feasibility / Measuring (early)', 'Under Review', 'Both indicate active evaluation without firm commitment'],
  ['(No old equivalent)', 'Open to Exploring [NEW]', 'New option - no 2026 responses map here. Rewards openness without implying active evaluation'],
  ['Not able to offer / Not in place / Not measured / Not able to utilize', 'Not Planned', 'Both indicate a considered decision not to proceed'],
  ['Unsure (all dimensions)', 'Unsure (currently hidden)', 'Hidden for launch - needs scoring decision before re-enabling'],
];
const ws2 = XLSX.utils.aoa_to_sheet(scaleData);
ws2['!cols'] = [
  { wch: 60 },
  { wch: 70 },
  { wch: 50 },
];
XLSX.utils.book_append_sheet(wb, ws2, 'Scale Mapping');

// ===== Sheet 3: Change Summary =====
const changeData = [
  ['2027 Change Summary'],
  [],
  ['NEW Elements Added'],
  ['Dimension', 'Element', 'Details'],
  ['D1', 'Guaranteed full salary and health insurance continuation for a defined period', 'With conditional follow-up question on duration (up to 3 months through no defined limit)'],
  ['D1', 'Guaranteed job protection for a defined period', 'With conditional follow-up question on duration (same scale as above)'],
  [],
  ['Elements REMOVED'],
  ['Dimension', 'Element', 'Reason'],
  ['D4', 'Nutrition coaching', 'Removed per client request'],
  ['D5', 'Priority parking', 'Removed per client request'],
  ['D5', 'Remote work capability', 'Duplicate of D1 "Remote work options for on-site employees"'],
  ['D5', 'Flexible scheduling options', 'Similar to D8 flexible work arrangements'],
  ['D8', 'Flexible work arrangements during treatment', 'Overlaps with D1 flexible hours + other D8 elements'],
  [],
  ['Response Scale Changes (2026 to 2027)'],
  ['Change', 'Details', 'Status'],
  ['Unified to 6 options', 'In Place, In Development, Under Review, Open to Exploring (new), Not Planned, Unsure', 'Active (Unsure hidden for launch)'],
  ['"Open to Exploring" added', 'New option - rewards openness without implying active evaluation', 'Active'],
  ['"Unsure" hidden', 'Hidden for launch pending scoring decision with Rebecca', 'Temporarily hidden'],
  [],
  ['Other Updates'],
  ['Area', 'Change', 'Details'],
  ['Landing page', 'New headline', '"The 2027 Survey is Now Open"'],
  ['Completion email', 'Updated timeline', 'Survey close: Oct 1, 2026 | Index: Jan 2027 | Reports: Feb 2027'],
  ['Completion email', 'Employee survey wording', '"optional employee survey, $500"'],
  ['Invoice email', 'Year references', 'Updated from 2026 to 2027'],
  ['D1 wording', 'Clarified insurance type', '"health insurance" (not just "insurance") per Rebecca'],
  [],
  ['Flexible Work Elements (Kept - Different Contexts)'],
  ['Element', 'Dimension', 'Context'],
  ['Flexible work hours during treatment', 'D1 - Medical Leave & Flexibility', 'Hours/scheduling during active treatment'],
  ['Flexible work arrangements for caregivers', 'D10 - Caregiver & Family Support', 'Caregiver-specific flexibility'],
];
const ws3 = XLSX.utils.aoa_to_sheet(changeData);
ws3['!cols'] = [
  { wch: 45 },
  { wch: 65 },
  { wch: 55 },
];
XLSX.utils.book_append_sheet(wb, ws3, 'Change Summary');

XLSX.writeFile(wb, 'C:/Users/JohnB/Downloads/CAC-Elements-and-Scale-Mapping.xlsx');
console.log('Created: C:/Users/JohnB/Downloads/CAC-Elements-and-Scale-Mapping.xlsx');
